export const mutualfunds = {
    "title": "Mututal Funds",
    "Content": "A mutual fund is a type of financial vehicle made up of a pool of money collected from many investors to invest in securities like stocks, bonds, money market instruments, and other assets. Mutual funds are operated by professional money managers, who allocate the fund's assets and attempt to produce capital gains or income for the fund's investors. A mutual fund's portfolio is structured and maintained to match the investment objectives stated in its prospectus. Mutual funds give small or individual investors access to professionally managed portfolios of equities, bonds, and other securities. Each shareholder, therefore, participates proportionally in the gains or losses of the fund. Mutual funds invest in a vast number of securities, and performance is usually tracked as the change in the total market cap of the fund—derived by the aggregating performance of the underlying investments.",
}
export const etfs = {
    "title": "etfs",
    "Content": "An ETF is called an exchange-traded fund because it's traded on an exchange just like stocks are. The price of an ETF's shares will change throughout the trading day as the shares are bought and sold on the market. This is unlike mutual funds, which are not traded on an exchange, and which trade only once per day after the markets close. Additionally, ETFs tend to be more cost-effective and more liquid compared to mutual funds. An ETF is a type of fund that holds multiple underlying assets, rather than only one like a stock does. Because there are multiple assets within an ETF, they can be a popular choice for diversification. ETFs can thus contain many types of investments, including stocks, commodities, bonds, or a mixture of investment types. An ETF can own hundreds or thousands of stocks across various industries, or it could be isolated to one particular industry or sector. Some funds focus on only U.S. offerings, while others have a global outlook. For example, banking-focused ETFs would contain stocks of various banks across the industry. An ETF is a marketable security, meaning it has a share price that allows it to be easily bought and sold on exchanges throughout the day, and it can be sold short. In the United States, most ETFs are set up as open-ended funds and are subject to the Investment Company Act of 1940 except where subsequent rules have modified their regulatory requirements. Open-end funds do not limit the number of investors involved in the product.",
}
export const equity = {
    "title": "equity",
    "Content": "Equity, typically referred to as shareholders' equity (or owners' equity for privately held companies), represents the amount of money that would be returned to a company's shareholders if all of the assets were liquidated and all of the company's debt was paid off in the case of liquidation. In the case of acquisition, it is the value of company sales minus any liabilities owed by the company not transferred with the sale. In addition, shareholder equity can represent the book value of a company. Equity can sometimes be offered as payment-in-kind. It also represents the pro-rata ownership of a company's shares. Equity can be found on a company's balance sheet and is one of the most common pieces of data employed by analysts to assess a company's financial health.",
}
export const debtRatio = {
    "title": "debt ratio",
    "Content": "The term debt ratio refers to a financial ratio that measures the extent of a company's leverage. The debt ratio is defined as the ratio of total debt to total assets, expressed as a decimal or percentage. It can be interpreted as the proportion of a company's assets that are financed by debt. A ratio greater than 1 shows that a considerable portion of a company's debt is funded by assets, which means the company has more liabilities than assets. A high ratio indicates that a company may be at risk of default on its loans if interest rates suddenly rise. A ratio below 1 means that a greater portion of a company's assets is funded by equity.",
}
export const insurance = {
    "title": "waiver of premium",
    "Content": "A waiver of premium rider is an insurance policy clause that waives premium payments if the policyholder becomes critically ill, seriously injured, or physically impaired. Other stipulations may apply, such as meeting specific health and age requirements. Policyholders may want to purchase a waiver if they are concerned about making ends meet if they are injured on the job. Most waiver of premium riders contain a waiting period during which there can be no claim of benefits. If physically impaired or hurt during the waiting period, the policyholder may receive a full refund of paid premiums. Without a waiting period, the insurer's assumed risk increases substantially, and devastating losses could result. Applicants with pre-existing disabilities aren't permitted to obtain benefits. Placing a pre-existing limitation avoids the possibility of writing a policy that would not see premium payments from the high-risk applicants.",
}
export const lesson0 = {
    "data": "Financial literacy is important for you because it will equip you with the knowledge and skill to manage your money effectively. The absence of the same will lack a strong foundation in terms of your actions and decisions concerning savings and investments. However, financial literacy will help you in understanding financial concepts in a better way and enable you to manage your finances efficiently. It will also help you in effective money management, financial decisions and achieving financial stability. At the same time, financial literacy will provide in-depth knowledge of financial education and various strategies that are crucial for financial growth and success. This will enable you to be debt-free by adopting the best debt strategies. Four components needed to understand financial literacy better are budgeting, debt, saving and investment. "
}